### ISSUE TITLE
Disable printer sharing

### ISSUE THREAD

**Issue by socialsti** [mikaellofgren/PrinterSetup#1]
First of all, great tool!

Any idea how I can disable printer sharing by default, the sharing box is checked when adding the printer.

**Comment by mikaellofgren** [comment]
Hi
Thanks. This option should disable printer sharing.
 -o printer-is-shared=False
What OS are you on? Might be a GUI bug?

**Comment by socialsti** [comment]
Wel apparently it was a Gui bug indeed. Worked flawless after re-adding the printer! Thanks again!
