### ISSUE TITLE
App crashes instantly on Intel on startup

### ISSUE THREAD

**Issue by pexner** [mikaellofgren/PrinterSetup#5]
App crashes instantly on Intel on startup

**Comment by mikaellofgren** [comment]
Hi!
Can you have a look if any files exist in `/Library/Printers/PPDs`
And what macOS Version?

**Comment by pexner** [comment]
no files directly in `Library/Printers/PPDs`- only the usual `Contents/Resources/`directories with many PPDs inside.
macOS 12.6.3
Starting via commandline `/Applications/PrinterSetup.app/Contents/MacOS/PrinterSetup` exits with
`Illegal instruction: 4`

**Comment by mikaellofgren** [comment]
Thanks, just tried a with a Intel 12.6.3 and with no files in `/Library/Printers/PPDs/Contents/Resources/` 

Could you try to rename /Library/Printers/PPDs/Contents/Resources to /Library/Printers/PPDs/Contents/Resources_old and then make an empty Resources folder. Maybe it's having some problem "reading" some PPD files. That's sometimes has been an issue which I don't haven't found a way to find out why.

**Comment by pexner** [comment]
Did that. Still crashing.

**Comment by pexner** [comment]
What should `~/Library/Application Support/PrinterSetup/ppds.txt`contain?
It is (and always was) empty. Remving it, commandline-start of App complains then `no such file or diectory`.

**Comment by pexner** [comment]
Found the culprit.
I had a virtual "Print to VipRiser" printer from VipRiser `https://onflapp.github.io/blog/pages/VipRiser` installed.
Removing it from System Preferences allowed PrinterSetup to start.
Reinstalling the "Print to VipRiser" printer -> crash on PrinterSetup startup.
I finally removed VipRiser. Thank you Mikael for your wonderful App.

**Comment by mikaellofgren** [comment]
Thanks and great to hear!
